name: CI
on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: NPM Packages
        run: npm install
        
      # Execute unit tests
      - name: Unit Test
        run: npm test

      - name: eslint
        run: npm run lint
